version: "3.8"
services:
  hornet-storage:
    image: hornet-storage
    environment:
      PORT: 2700
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 2700:2700
    command: "./hornet-storage"